services:
  - type: web
    name: voice-bot
    env: python
    dockerfilePath: Dockerfile  # Point to your Dockerfile here
    buildCommand: |
      # You can add any necessary build commands, like installing dependencies if required
      pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:8000 Backend.server:app
